dist: xenial
language: python
cache: pip
python:
- '3.6'
- '3.7'
- 3.8-dev
- nightly
matrix:
  allow_failures:
  - python: 3.8-dev
  - python: nightly
install:
- pip install flit
- flit install --symlink
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
